services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fast-api-backend
    restart: always
    expose:
      - "8000"
    env_file:
      - ./api/.env
    environment:
      FORWARDED_ALLOW_IPS: "*"
    depends_on:
      - mongodb
    volumes:
      - ./api/app/static:/app/app/static

  mongodb:
    image: mongo:latest
    container_name: api-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: hostelmanager

  nginx:
    image: nginx:alpine
    container_name: api-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./api/app/static:/usr/share/nginx/html/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always

volumes:
  mongo-data:
